FROM ubuntu:jammy

# Set environment variables
ENV DEBIAN_FRONTEND noninteractive

# Install build dependencies
RUN apt-get update && apt-get install -y \
    g++ \
    python3 \
    python3-pip \ 
    ffmpeg \
    wget \
    curl && \
    rm -rf /var/lib/apt/lists/*  # clean up apt cache to reduce layer size
